# Definice proměnných
IMAGE_NAME=migration-startup
CONTAINER_NAME=migration-container

migration-init:
	@echo "Starting MigrationStartup container..."
	docker run --name $(CONTAINER_NAME) --rm $(IMAGE_NAME)
