
server:
  port: 5003
  host: localhost
db:
  mongo:
    username: root
    database: hackathon-mongo
    host: hackathon-mongo
    port: 27017
    name: hackathon-mongo

  postgres:
    username: root
    database: hackathon-postgres
    host: 0.0.0.0
    port: 5200
    name: hackathon-postgres

services:
  auth: 5001
  user: 5002
  support: 5004

    