
server:
  port: 8080
  host: localhost
db:
  mongo:
    username: root
    database: hackathon-mongo
    host: localhost
    port: 27017
    name: hackathon-mongo

  postgres:
    username: root
    database: hackathon-postgres
    host: localhost
    port: 5432
    name: hackathon-postgres