

run:
	go run cmd/main.go

run-dev:
	docker build -t hackathon-message-service .
	docker run -p 5003:5003 hackathon-message-service

run-prod:
	docker build -t hackathon-message-service .
	docker run -p 5003:5003 hackathon-message-service
